In [1]:
import sklearn
import numpy as np
import pandas
import torch
import sklearn.datasets
import sklearn.preprocessing
import helpers
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import OneClassSVM
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, precision_score, recall_score, precision_recall_curve, roc_auc_score, f1_score, make_scorer, auc, average_precision_score

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# KDDCUP Dataset
Classes:   
- 'normal' : Anomalous (1)
- Else : Non-anomalous (0)


duration: continuous.  
protocol_type: symbolic.  
service: symbolic.  
flag: symbolic.  
src_bytes: continuous.  
dst_bytes: continuous.  
land: symbolic.  
wrong_fragment: continuous.  
urgent: continuous.  
hot: continuous.  
num_failed_logins: continuous.  
logged_in: symbolic.  
num_compromised: continuous.  
root_shell: continuous.  
su_attempted: continuous.  
num_root: continuous.  
num_file_creations: continuous.  
num_shells: continuous.  
num_access_files: continuous.  
num_outbound_cmds: continuous.  
is_host_login: symbolic.  
is_guest_login: symbolic.  
count: continuous.  
srv_count: continuous.  
serror_rate: continuous.  
srv_serror_rate: continuous.  
rerror_rate: continuous.  
srv_rerror_rate: continuous.  
same_srv_rate: continuous.  
diff_srv_rate: continuous.  
srv_diff_host_rate: continuous.  
dst_host_count: continuous.  
dst_host_srv_count: continuous.  
dst_host_same_srv_rate: continuous.  
dst_host_diff_srv_rate: continuous.  
dst_host_same_src_port_rate: continuous.  
dst_host_srv_diff_host_rate: continuous.  
dst_host_serror_rate: continuous.  
dst_host_srv_serror_rate: continuous.  
dst_host_rerror_rate: continuous.  
dst_host_srv_rerror_rate: continuous.

In [2]:
X_kddcup, Y_kddcup = helpers.load_KDD_trainset()
X_kddcup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Data columns (total 42 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       494021 non-null  int64
 1   1       494021 non-null  object
 2   2       494021 non-null  object
 3   3       494021 non-null  object
 4   4       494021 non-null  int64
 5   5       494021 non-null  int64
 6   6       494021 non-null  int64
 7   7       494021 non-null  int64
 8   8       494021 non-null  int64
 9   9       494021 non-null  int64
 10  10      494021 non-null  int64
 11  11      494021 non-null  int64
 12  12      494021 non-null  int64
 13  13      494021 non-null  int64
 14  14      494021 non-null  int64
 15  15      494021 non-null  int64
 16  16      494021 non-null  int64
 17  17      494021 non-null  int64
 18  18      494021 non-null  int64
 19  19      494021 non-null  int64
 20  20      494021 non-null  int64
 21  21      494021 non-null  int64
 22  22      494021 non-null  int64
 23  23      494021 non-null  int64
 24  24      494021 non-null  float64
 25  25      494021 non-null  float64
 26  26      494021 non-null  float64
 27  27      494021 non-null  float64
 28  28      494021 non-null  float64
 29  29      494021 non-null  float64
 30  30      494021 non-null  float64
 31  31      494021 non-null  int64
 32  32      494021 non-null  int64
 33  33      494021 non-null  float64
 34  34      494021 non-null  float64
 35  35      494021 non-null  float64
 36  36      494021 non-null  float64
 37  37      494021 non-null  float64
 38  38      494021 non-null  float64
 39  39      494021 non-null  float64
 40  40      494021 non-null  float64
 41  41      494021 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 158.3+ MB

In [3]:
Y_kddcup

0         normal.
1         normal.
2         normal.
3         normal.
4         normal.
           ...
494016    normal.
494017    normal.
494018    normal.
494019    normal.
494020    normal.
Name: 41, Length: 494021, dtype: object

In [4]:
Y_kddcup.value_counts()

41
smurf.              280790
neptune.            107201
normal.              97278
back.                 2203
satan.                1589
ipsweep.              1247
portsweep.            1040
warezclient.          1020
teardrop.              979
pod.                   264
nmap.                  231
guess_passwd.           53
buffer_overflow.        30
land.                   21
warezmaster.            20
imap.                   12
rootkit.                10
loadmodule.              9
ftp_write.               8
multihop.                7
phf.                     4
perl.                    3
spy.                     2
Name: count, dtype: int64

Normal is treated as anomalous in this dataset

In [5]:
Y_kddcup = Y_kddcup.apply(lambda x: 1 if x=='normal.' else 0)

In [6]:
Y_kddcup.value_counts()

41
0    396743
1     97278
Name: count, dtype: int64

In [7]:
num_categorical = X_kddcup.select_dtypes(include=['object', 'category']).shape[1]
num_categorical

4

In [8]:
X_kddcup = X_kddcup.drop(X_kddcup.columns[-1], axis=1)

Need to handle nominal attributes

In [9]:
X_kddcup_onehot = pandas.get_dummies(X_kddcup,dtype=int)
X_kddcup_onehot.head()

,0,4,5,6,7,8,9,10,11,12,...,3_REJ,3_RSTO,3_RSTOS0,3_RSTR,3_S0,3_S1,3_S2,3_S3,3_SF,3_SH
0,0,181,5450,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,0,239,486,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,0,235,1337,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,219,1337,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,217,2032,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0

In [10]:
X_kddcup_onehot.info(verbose=True)
X_kddcup_onehot.columns = X_kddcup_onehot.columns.astype(str)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Data columns (total 118 columns):
 #    Column         Dtype
---   ------         -----
 0    0              int64
 1    4              int64
 2    5              int64
 3    6              int64
 4    7              int64
 5    8              int64
 6    9              int64
 7    10             int64
 8    11             int64
 9    12             int64
 10   13             int64
 11   14             int64
 12   15             int64
 13   16             int64
 14   17             int64
 15   18             int64
 16   19             int64
 17   20             int64
 18   21             int64
 19   22             int64
 20   23             int64
 21   24             float64
 22   25             float64
 23   26             float64
 24   27             float64
 25   28             float64
 26   29             float64
 27   30             float64
 28   31             int64
 29   32             int64
 30   33             float64
 31   34             float64
 32   35             float64
 33   36             float64
 34   37             float64
 35   38             float64
 36   39             float64
 37   40             float64
 38   1_icmp         int64
 39   1_tcp          int64
 40   1_udp          int64
 41   2_IRC          int64
 42   2_X11          int64
 43   2_Z39_50       int64
 44   2_auth         int64
 45   2_bgp          int64
 46   2_courier      int64
 47   2_csnet_ns     int64
 48   2_ctf          int64
 49   2_daytime      int64
 50   2_discard      int64
 51   2_domain       int64
 52   2_domain_u     int64
 53   2_echo         int64
 54   2_eco_i        int64
 55   2_ecr_i        int64
 56   2_efs          int64
 57   2_exec         int64
 58   2_finger       int64
 59   2_ftp          int64
 60   2_ftp_data     int64
 61   2_gopher       int64
 62   2_hostnames    int64
 63   2_http         int64
 64   2_http_443     int64
 65   2_imap4        int64
 66   2_iso_tsap     int64
 67   2_klogin       int64
 68   2_kshell       int64
 69   2_ldap         int64
 70   2_link         int64
 71   2_login        int64
 72   2_mtp          int64
 73   2_name         int64
 74   2_netbios_dgm  int64
 75   2_netbios_ns   int64
 76   2_netbios_ssn  int64
 77   2_netstat      int64
 78   2_nnsp         int64
 79   2_nntp         int64
 80   2_ntp_u        int64
 81   2_other        int64
 82   2_pm_dump      int64
 83   2_pop_2        int64
 84   2_pop_3        int64
 85   2_printer      int64
 86   2_private      int64
 87   2_red_i        int64
 88   2_remote_job   int64
 89   2_rje          int64
 90   2_shell        int64
 91   2_smtp         int64
 92   2_sql_net      int64
 93   2_ssh          int64
 94   2_sunrpc       int64
 95   2_supdup       int64
 96   2_systat       int64
 97   2_telnet       int64
 98   2_tftp_u       int64
 99   2_tim_i        int64
 100  2_time         int64
 101  2_urh_i        int64
 102  2_urp_i        int64
 103  2_uucp         int64
 104  2_uucp_path    int64
 105  2_vmnet        int64
 106  2_whois        int64
 107  3_OTH          int64
 108  3_REJ          int64
 109  3_RSTO         int64
 110  3_RSTOS0       int64
 111  3_RSTR         int64
 112  3_S0           int64
 113  3_S1           int64
 114  3_S2           int64
 115  3_S3           int64
 116  3_SF           int64
 117  3_SH           int64
dtypes: float64(15), int64(103)
memory usage: 444.8 MB

There is a separate test set, so we train on the full dataset instead of splitting

In [11]:
X_kddcup_train = X_kddcup_onehot[Y_kddcup==0]
Y_kddcup_anomalies = Y_kddcup[Y_kddcup==1]

In [12]:
X_kddcup_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 396743 entries, 744 to 490964
Columns: 118 entries, 0 to 3_SH
dtypes: float64(15), int64(103)
memory usage: 360.2 MB

In [13]:
def output_formatter(predictions):
    predictions = np.where(predictions == 1, 0, 1)
    return predictions

The dataset is huge, taking a subsamples to train

In [14]:
from itertools import product
sample_size = 100000
anomaly_ratio = 0.2
models = []

gammas = ['scale', 'auto', 0.001, 0.0001]
nus = [0.0001, 0.0005, 0.001, 0.01]
models = []
avg_scores = []
random_states=[41,42,43]
for (gamma, nu) in product(gammas, nus):
    model = Pipeline([
            ("scaler", StandardScaler()),
            ("svm_clf", OneClassSVM(kernel='rbf', gamma=gamma, nu=nu))
        ])
    models.append(model)
    p,r,f = 0, 0, 0
    for rs in random_states:
        shuffled_sampled = X_kddcup_train.sample(frac=1, random_state=rs).sample(n=sample_size, random_state=rs)
        anomalies = Y_kddcup_anomalies.sample(n=int(np.floor(0.2*anomaly_ratio*sample_size)), random_state=rs)
        # 80000 train, 20000 validate
        X_sample, X_test, Y_sample, Y_test = train_test_split(shuffled_sampled, Y_kddcup.iloc[shuffled_sampled.index], test_size=0.2, random_state=42)
        X_test_anomalies = pandas.concat([X_test, X_kddcup_onehot.iloc[anomalies.index]], ignore_index=True)
        Y_test_anomalies = pandas.concat([Y_test, anomalies], ignore_index=True)
        
        # Train on a shuffled sample of normal data to find promising models
        model.fit(X_sample)        

        predictions = output_formatter(model.predict(X_test_anomalies))
        p += precision_score(Y_test_anomalies, predictions) 
        r += recall_score(Y_test_anomalies, predictions)
        f += f1_score(Y_test_anomalies, predictions)
    avg_scores.append(
        [p/len(random_states), r/len(random_states), f/len(random_states)])

In [15]:
avg_scores = np.array(avg_scores)
avg_scores

array([[0.70295761, 0.91433333, 0.73512074],
       [0.70832395, 0.91058333, 0.73838919],
       [0.71377694, 0.91141667, 0.74098689],
       [0.94632515, 0.97108333, 0.95854269],
       [0.70153534, 0.85458333, 0.70391498],
       [0.70529074, 0.89741667, 0.73201609],
       [0.48118698, 0.89533333, 0.55448585],
       [0.71230768, 0.96808333, 0.76934476],
       [0.75190789, 0.105     , 0.18354696],
       [0.83693978, 0.10466667, 0.18543733],
       [0.85196733, 0.10475   , 0.18588743],
       [0.71975581, 0.13408333, 0.22604261],
       [0.80393741, 0.02358333, 0.04537789],
       [0.84040044, 0.024     , 0.04615155],
       [0.80317823, 0.04891667, 0.09002488],
       [0.67425467, 0.10833333, 0.18666108]])

In [16]:
indices_promising_models = np.where(avg_scores[:, 2] > 0.90)[0]
avg_scores[avg_scores[:,2] > .70]

array([[0.70295761, 0.91433333, 0.73512074],
       [0.70832395, 0.91058333, 0.73838919],
       [0.71377694, 0.91141667, 0.74098689],
       [0.94632515, 0.97108333, 0.95854269],
       [0.70153534, 0.85458333, 0.70391498],
       [0.70529074, 0.89741667, 0.73201609],
       [0.71230768, 0.96808333, 0.76934476]])

**Load Test Data**

In [17]:
X_kddcup_test, Y_kddcup_test = helpers.load_KDD_testset()

Y_kddcup_test.value_counts()

41
smurf.              164091
normal.              60593
neptune.             58001
snmpgetattack.        7741
mailbomb.             5000
guess_passwd.         4367
snmpguess.            2406
satan.                1633
warezmaster.          1602
back.                 1098
mscan.                1053
apache2.               794
processtable.          759
saint.                 736
portsweep.             354
ipsweep.               306
httptunnel.            158
pod.                    87
nmap.                   84
buffer_overflow.        22
multihop.               18
named.                  17
sendmail.               17
ps.                     16
xterm.                  13
rootkit.                13
teardrop.               12
xlock.                   9
land.                    9
xsnoop.                  4
ftp_write.               3
perl.                    2
phf.                     2
udpstorm.                2
worm.                    2
loadmodule.              2
sqlattack.               2
imap.                    1
Name: count, dtype: int64

In [18]:
# Convert labels to generalized convention
Y_kddcup_test = Y_kddcup_test.apply(lambda x: 1 if x == 'normal.' else 0)

# Drop label columns from data
X_kddcup_test = X_kddcup_test.drop(X_kddcup_test.columns[-1], axis=1)

# One-hot encode all non-continuous columns
X_kddcup_test_onehot = pandas.get_dummies(X_kddcup_test, dtype=int)
X_kddcup_test_onehot.columns = X_kddcup_test_onehot.columns.astype(str)

Y_kddcup_test.value_counts()

41
0    250436
1     60593
Name: count, dtype: int64

In [19]:
X_kddcup_test_onehot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311029 entries, 0 to 311028
Columns: 117 entries, 0 to 3_SH
dtypes: float64(15), int64(102)
memory usage: 277.6 MB

In [20]:
Y_kddcup_test.info()

<class 'pandas.core.series.Series'>
RangeIndex: 311029 entries, 0 to 311028
Series name: 41
Non-Null Count   Dtype
--------------   -----
311029 non-null  int64
dtypes: int64(1)
memory usage: 2.4 MB

In [21]:
X_kddcup_test_onehot.index == Y_kddcup_test.index

array([ True,  True,  True, ...,  True,  True,  True], shape=(311029,))

In [22]:
X_kddcup_test_onehot.columns

Index(['0', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       ...
       '3_REJ', '3_RSTO', '3_RSTOS0', '3_RSTR', '3_S0', '3_S1', '3_S2', '3_S3',
       '3_SF', '3_SH'],
      dtype='object', length=117)

In [23]:
X_kddcup_train.columns

Index(['0', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       ...
       '3_REJ', '3_RSTO', '3_RSTOS0', '3_RSTR', '3_S0', '3_S1', '3_S2', '3_S3',
       '3_SF', '3_SH'],
      dtype='object', length=118)

In [24]:
X_kddcup_test_onehot.columns == X_kddcup_train.columns

ValueError: Lengths must match to compare

**Dealing with mismatch hot encoded columns**

In [25]:
X_kddcup, _ = helpers.load_KDD_trainset()
X_kddcup = X_kddcup.drop(X_kddcup.columns[-1], axis=1)

In [26]:
X_combined = pandas.concat([X_kddcup, X_kddcup_test], axis=0)

In [27]:
X_combined_onehot = pandas.get_dummies(X_combined, dtype=int)
X_combined_onehot.columns = X_combined_onehot.columns.astype(str)

X_kddcup_train_onehot = X_combined_onehot.iloc[:len(X_kddcup), :]

# Selecting exclusively normal  data to train on
X_kddcup_train_onehot = X_kddcup_train_onehot[Y_kddcup == 0]

X_kddcup_test_onehot = X_combined_onehot.iloc[len(X_kddcup):, :]

X_kddcup_train_onehot

,0,4,5,6,7,8,9,10,11,12,...,3_REJ,3_RSTO,3_RSTOS0,3_RSTR,3_S0,3_S1,3_S2,3_S3,3_SF,3_SH
744,184,1511,2957,0,0,0,3,0,1,2,...,0,0,0,0,0,0,0,0,1,0
745,305,1735,2766,0,0,0,3,0,1,2,...,0,0,0,0,0,0,0,0,1,0
4049,79,281,1301,0,0,0,2,0,1,1,...,0,0,0,0,0,0,0,0,1,0
4113,25,269,2333,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
7601,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490960,0,28,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
490961,0,28,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
490962,0,28,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
490963,0,28,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
490964,0,28,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [28]:
len(Y_kddcup_test) == len(X_kddcup_test_onehot)

True

In [29]:
scores=[]
for i in indices_promising_models:
    models[i].fit(X_kddcup_train_onehot)
    
    predictions = output_formatter(models[i].predict(X_kddcup_test_onehot))
    scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
        predictions), f1_score(Y_kddcup_test, predictions)])

In [30]:
scores

[[0.31776923360917286, 0.9943392801148647, 0.4816224080321028]]

Clearly the best model from subsample, performed significantly worse, signalling potential subsample bias / subsample that did not retain the original dataset distribution, or the training overfitted the smaller sample.  

The randomness in subsampling I employed likely have changed the innate distribution of the bigger dataset. Should try to stratified sample instead

In [38]:
avg_scores

array([[0.70295761, 0.91433333, 0.73512074],
       [0.70832395, 0.91058333, 0.73838919],
       [0.71377694, 0.91141667, 0.74098689],
       [0.94632515, 0.97108333, 0.95854269],
       [0.70153534, 0.85458333, 0.70391498],
       [0.70529074, 0.89741667, 0.73201609],
       [0.48118698, 0.89533333, 0.55448585],
       [0.71230768, 0.96808333, 0.76934476],
       [0.75190789, 0.105     , 0.18354696],
       [0.83693978, 0.10466667, 0.18543733],
       [0.85196733, 0.10475   , 0.18588743],
       [0.71975581, 0.13408333, 0.22604261],
       [0.80393741, 0.02358333, 0.04537789],
       [0.84040044, 0.024     , 0.04615155],
       [0.80317823, 0.04891667, 0.09002488],
       [0.67425467, 0.10833333, 0.18666108]])

In [36]:
model2 = models[0].fit(X_kddcup_train_onehot)
predictions = output_formatter(model2.predict(X_kddcup_test_onehot))
scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
                                                                            predictions), f1_score(Y_kddcup_test, predictions)])

scores[0] is the best model (obtained from subsample training)

In [37]:
scores

[[0.31776923360917286, 0.9943392801148647, 0.4816224080321028],
 [0.6284007061699335, 0.6873071146832143, 0.6565352419087856]]

In [39]:
model3 = models[1].fit(X_kddcup_train_onehot)
predictions = output_formatter(model3.predict(X_kddcup_test_onehot))
scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
                                                                         predictions), f1_score(Y_kddcup_test, predictions)])

In [40]:
scores

[[0.31776923360917286, 0.9943392801148647, 0.4816224080321028],
 [0.6284007061699335, 0.6873071146832143, 0.6565352419087856],
 [0.6680946888559345, 0.8029970458633836, 0.7293604455070791]]

In [41]:
model4 = models[2].fit(X_kddcup_train_onehot)
predictions = output_formatter(model4.predict(X_kddcup_test_onehot))
scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
                                                                         predictions), f1_score(Y_kddcup_test, predictions)])

In [42]:
scores

[[0.31776923360917286, 0.9943392801148647, 0.4816224080321028],
 [0.6284007061699335, 0.6873071146832143, 0.6565352419087856],
 [0.6680946888559345, 0.8029970458633836, 0.7293604455070791],
 [0.6687560005486216, 0.8046969121845757, 0.7304554953821263]]

In [43]:
model5 = models[4].fit(X_kddcup_train_onehot)
predictions = output_formatter(model5.predict(X_kddcup_test_onehot))
scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
                                                                         predictions), f1_score(Y_kddcup_test, predictions)])

In [44]:
model6 = models[5].fit(X_kddcup_train_onehot)
predictions = output_formatter(model6.predict(X_kddcup_test_onehot))
scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
                                                                         predictions), f1_score(Y_kddcup_test, predictions)])

In [45]:
model7 = models[7].fit(X_kddcup_train_onehot)
predictions = output_formatter(model7.predict(X_kddcup_test_onehot))
scores.append([precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test,
                                                                         predictions), f1_score(Y_kddcup_test, predictions)])

In [46]:
scores

[[0.31776923360917286, 0.9943392801148647, 0.4816224080321028],
 [0.6284007061699335, 0.6873071146832143, 0.6565352419087856],
 [0.6680946888559345, 0.8029970458633836, 0.7293604455070791],
 [0.6687560005486216, 0.8046969121845757, 0.7304554953821263],
 [0.23480830915677775, 0.7840674665390391, 0.3613896030792168],
 [0.27559464344491863, 0.787632234746588, 0.40831779059222123],
 [0.6835837887067395, 0.9909725545855131, 0.8090653695606772]]

Model 7 exhibit the best f1_score, keep the 7th model

In [49]:
best_model = models[7]

predictions = output_formatter(best_model.predict(X_kddcup_test_onehot))
[precision_score(Y_kddcup_test, predictions), recall_score(Y_kddcup_test, predictions), f1_score(Y_kddcup_test, predictions)]

[0.6835837887067395, 0.9909725545855131, 0.8090653695606772]

In [50]:
best_model.get_params()

{'memory': None,
 'steps': [('scaler', StandardScaler()),
  ('svm_clf', OneClassSVM(gamma='auto', nu=0.01))],
 'transform_input': None,
 'verbose': False,
 'scaler': StandardScaler(),
 'svm_clf': OneClassSVM(gamma='auto', nu=0.01),
 'scaler__copy': True,
 'scaler__with_mean': True,
 'scaler__with_std': True,
 'svm_clf__cache_size': 200,
 'svm_clf__coef0': 0.0,
 'svm_clf__degree': 3,
 'svm_clf__gamma': 'auto',
 'svm_clf__kernel': 'rbf',
 'svm_clf__max_iter': -1,
 'svm_clf__nu': 0.01,
 'svm_clf__shrinking': True,
 'svm_clf__tol': 0.001,
 'svm_clf__verbose': False}

# Isolation forest: in the context of anomaly detection

In [61]:
from sklearn.ensemble import IsolationForest

In [62]:
X_kddcup_train_onehot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 396743 entries, 744 to 490964
Columns: 119 entries, 0 to 3_SH
dtypes: float64(15), int64(104)
memory usage: 363.2 MB

In [64]:
X_kddcup_test_onehot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311029 entries, 0 to 311028
Columns: 119 entries, 0 to 3_SH
dtypes: float64(15), int64(104)
memory usage: 284.8 MB

In [63]:
Y_kddcup_test.info()

<class 'pandas.core.series.Series'>
RangeIndex: 311029 entries, 0 to 311028
Series name: 41
Non-Null Count   Dtype
--------------   -----
311029 non-null  int64
dtypes: int64(1)
memory usage: 2.4 MB

In [75]:
len(Y_kddcup_anomalies) / len(X_kddcup)

0.19691065764410826

Parameters to do grid search

In [77]:
contanmination_factors = [
    float(len(Y_kddcup_anomalies) / len(X_kddcup)), 0.01, 0.001]
num_itrees = [50, 100, 150]
max_samples = [128, 'auto', 512]
max_features = [8, 10, 12, 14]

In [78]:
from itertools import product
models = []
avg_scores = []
random_states = [40, 50, 60]
for (contanmination_factor, n_tree, max_sample, max_feature) in product(contanmination_factors, num_itrees, max_samples, max_features):
    model = IsolationForest(n_estimators=n_tree, contamination=contanmination_factor,
                            max_samples=max_sample, max_features=max_feature, n_jobs=-1, random_state=42)
    p, r, f1 = 0, 0, 0
    models.append(model)
    for rs in random_states:
        model.fit(X_kddcup_train_onehot)
        predictions = output_formatter(
            model.predict(X_kddcup_test_onehot))

        p += precision_score(Y_kddcup_test, predictions)
        r += recall_score(Y_kddcup_test, predictions)
        f1 += f1_score(Y_kddcup_test, predictions)

    avg_scores.append(
        [p/len(random_states), r/len(random_states), f1/len(random_states)])

In [79]:
avg_scores = np.array(avg_scores)
avg_scores

array([[3.85058539e-01, 8.20688858e-01, 5.24178205e-01],
       [4.29556601e-01, 9.93035499e-01, 5.99701002e-01],
       [4.28371907e-01, 9.92127804e-01, 5.98380522e-01],
       [4.30683443e-01, 9.94240259e-01, 6.01018591e-01],
       [4.11241076e-01, 9.20254815e-01, 5.68453246e-01],
       [4.31215114e-01, 9.94471309e-01, 6.01578372e-01],
       [3.48775484e-01, 9.93250045e-01, 5.16266282e-01],
       [4.26496610e-01, 9.94471309e-01, 5.96971453e-01],
       [3.47669361e-01, 9.93250045e-01, 5.15053487e-01],
       [3.49105193e-01, 9.94471309e-01, 5.16792453e-01],
       [3.49886534e-01, 1.00000000e+00, 5.18393991e-01],
       [3.48903055e-01, 9.94471309e-01, 5.16570939e-01],
       [4.28234298e-01, 9.85278828e-01, 5.96995075e-01],
       [4.28962430e-01, 9.93233542e-01, 5.99157756e-01],
       [4.29689285e-01, 9.93250045e-01, 5.99869429e-01],
       [4.30577290e-01, 9.94471309e-01, 6.00957415e-01],
       [4.31563716e-01, 9.94256762e-01, 6.01878216e-01],
       [4.29916811e-01, 9.94471309e-01, 6.00313815e-01],
       [4.30137769e-01, 9.94471309e-01, 6.00529193e-01],
       [4.27370795e-01, 9.94471309e-01, 5.97827273e-01],
       [4.10557944e-01, 9.94471309e-01, 5.81180919e-01],
       [4.29070560e-01, 9.97144885e-01, 5.99973189e-01],
       [3.50473425e-01, 1.00000000e+00, 5.19037870e-01],
       [3.53087542e-01, 1.00000000e+00, 5.21899036e-01],
       [4.27362796e-01, 9.84536168e-01, 5.96011669e-01],
       [4.28435087e-01, 9.92754939e-01, 5.98556197e-01],
       [4.29409498e-01, 9.92985988e-01, 5.99548605e-01],
       [4.30392963e-01, 9.93250045e-01, 6.00554813e-01],
       [4.29870362e-01, 9.93250045e-01, 6.00045863e-01],
       [4.29995860e-01, 9.94256762e-01, 6.00351771e-01],
       [4.30091023e-01, 9.94256762e-01, 6.00444515e-01],
       [4.29428830e-01, 9.94256762e-01, 5.99798889e-01],
       [4.29772696e-01, 9.94471309e-01, 6.00173305e-01],
       [4.29308984e-01, 9.96303203e-01, 6.00053675e-01],
       [3.50254629e-01, 1.00000000e+00, 5.18797894e-01],
       [4.30993890e-01, 1.00000000e+00, 6.02369993e-01],
       [9.23161968e-02, 8.26828181e-03, 1.51772190e-02],
       [1.26439024e-01, 1.06943046e-02, 1.97206245e-02],
       [8.75995449e-02, 8.89541696e-03, 1.61507806e-02],
       [6.58700087e-02, 7.45960755e-03, 1.34015269e-02],
       [1.04293194e-01, 8.21877115e-03, 1.52368131e-02],
       [1.09777015e-01, 8.44982094e-03, 1.56918032e-02],
       [9.86639260e-02, 7.92170713e-03, 1.46658926e-02],
       [1.32530120e-01, 1.37969732e-02, 2.49921526e-02],
       [1.56148208e-01, 1.26582278e-02, 2.34180597e-02],
       [8.52736619e-02, 4.65400294e-03, 8.82629108e-03],
       [7.35658043e-02, 5.39666298e-03, 1.00556598e-02],
       [9.82318271e-02, 8.25177826e-03, 1.52246396e-02],
       [9.31047916e-02, 7.88870001e-03, 1.45450119e-02],
       [1.20455541e-01, 9.07695608e-03, 1.68817815e-02],
       [1.53647276e-01, 1.37309590e-02, 2.52090656e-02],
       [1.07700790e-01, 9.67108412e-03, 1.77484326e-02],
       [6.58205431e-02, 3.68029310e-03, 6.97081946e-03],
       [9.00500278e-02, 5.34715231e-03, 1.00948731e-02],
       [7.48856248e-02, 5.13260608e-03, 9.60677107e-03],
       [7.35143966e-02, 5.94128035e-03, 1.09940449e-02],
       [1.90027819e-01, 1.46551582e-02, 2.72117182e-02],
       [1.09444171e-01, 7.34408265e-03, 1.37645185e-02],
       [6.37417219e-02, 3.81232156e-03, 7.19435663e-03],
       [7.04914387e-02, 5.23162742e-03, 9.74035950e-03],
       [3.43708230e-02, 2.97064017e-03, 5.46863132e-03],
       [4.98480243e-02, 4.05987490e-03, 7.50824075e-03],
       [9.86758571e-02, 8.97793474e-03, 1.64584153e-02],
       [1.32638127e-01, 1.19650785e-02, 2.19500749e-02],
       [3.62387494e-02, 2.52504415e-03, 4.72112937e-03],
       [6.34467618e-02, 4.76952783e-03, 8.87210659e-03],
       [4.89009632e-02, 3.26770419e-03, 6.12604808e-03],
       [7.63405649e-02, 6.15582658e-03, 1.13929657e-02],
       [7.26006962e-02, 4.81903850e-03, 9.03814904e-03],
       [1.33214524e-01, 9.86912680e-03, 1.83768169e-02],
       [5.65407350e-02, 3.63078243e-03, 6.82339805e-03],
       [1.91046534e-01, 1.60579605e-02, 2.96257955e-02],
       [2.85714286e-02, 9.90213391e-05, 1.97358683e-04],
       [3.27272727e-02, 1.48532009e-04, 2.95721890e-04],
       [1.47492625e-03, 1.65035565e-05, 3.26418697e-05],
       [9.36329588e-04, 1.65035565e-05, 3.24354130e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.14285714e-03, 3.30071130e-05, 6.57105778e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.44827586e-02, 4.95106695e-05, 9.88793672e-05],
       [2.15053763e-02, 3.30071130e-05, 6.59130607e-05],
       [4.29184549e-03, 1.65035565e-05, 3.28806760e-05],
       [2.38568588e-02, 1.98042678e-04, 3.92824407e-04],
       [7.93650794e-03, 6.60142261e-05, 1.30939326e-04],
       [3.07455803e-03, 6.60142261e-05, 1.29253239e-04],
       [1.57728707e-03, 3.30071130e-05, 6.46610950e-05],
       [4.90196078e-03, 1.65035565e-05, 3.28963600e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.38967136e-03, 3.30071130e-05, 6.57829819e-05],
       [7.54716981e-03, 3.30071130e-05, 6.57267738e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.55754476e-03, 1.65035565e-05, 3.27954873e-05],
       [5.20833333e-03, 6.60142261e-05, 1.30375972e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.93542074e-03, 4.95106695e-05, 9.73788850e-05],
       [1.65562914e-03, 3.30071130e-05, 6.47238718e-05],
       [4.78468900e-03, 1.65035565e-05, 3.28936548e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.74025974e-03, 4.95106695e-05, 9.85205497e-05],
       [3.33333333e-03, 1.65035565e-05, 3.28444977e-05],
       [3.62318841e-03, 1.65035565e-05, 3.28574480e-05],
       [6.12244898e-03, 4.95106695e-05, 9.82270026e-05]])

In [80]:
indices = np.argsort(avg_scores[:, 2])[-3:][::-1]
indices

array([35, 16,  5])

In [82]:
scores = [avg_scores[i] for i in indices]
scores

[array([0.43099389, 1.        , 0.60236999]),
 array([0.43156372, 0.99425676, 0.60187822]),
 array([0.43121511, 0.99447131, 0.60157837])]

In [83]:
best_model = models[indices[0]]

In [84]:
best_model.get_params()

{'bootstrap': False,
 'contamination': 0.19691065764410826,
 'max_features': 14,
 'max_samples': 512,
 'n_estimators': 150,
 'n_jobs': -1,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

Current model performances:  
    - OC-SVM( kernel="rbf", gamma='auto', nu=0.01): F1_score ~ 0.81  
    - Isolation Forest ('contamination': 0.19691065764410826, 'max_features': 14, 'max_samples': 512, 'n_estimators': 150, 'n_jobs': -1) : F1_score ~ 0.60

# Autoencoder: in the context of Anomaly Detection
- Encoder learns to 'perfectly' encode normal data, decoder learns to 'perfectly' decode normal data
- Upon receiving anomalous data, the whole system fails encode / decode said data ==> treats it as anomaly based on reconstruction error > threshold